### ISSUE TITLE
PyreProtecc crashed (twice, maybe due to same reason)

### ISSUE THREAD

**Issue by ltw214171** [SaucyX/PyreProtecc#3]
[----------------|PyreSpy-ErrorReport|----------------]
Fault Type 0x:00000000C0000005
Fault address:0x00000001401AF73D
RAX:00000000001C2C61
RBX:0000000000000000
RCX:000000001C2C61A4
RDX:00000000000000A4
RSI:0000000007E1FC68
RDI:00000000D1A74B90
RBP:0000000007E1FC68
RSP:000000000765E980
R8:0000000007E1FD64
R9:0000000007E1FD64
R10:0000000000000508
R11:0000000144714CF0
R12:00007FF49E346898
R13:0000000000000000
R14:00000000000000FC
R15:0000000000000009
Stack-Info:0000000000000009 Stack-Info:0000000143D2FF40 Stack-Info:0000F8A0EC76F8FC Stack-Info:000000014001C24B Stack-Info:0000000000000508 Stack-Info:0000000000000009 Stack-Info:0000000000000001 Stack-Info:0000000143D2FF40 Stack-Info:000000000765EB19 Stack-Info:000000014001C017 Stack-Info:000000000765EAE8 Stack-Info:000000000765EA50 Stack-Info:000000000765EB19 Stack-Info:7FFFFFFF7FFFFFD1 Stack-Info:00007FF4313EEE50 Stack-Info:0000000007E1FC68 Stack-Info:0000000000000009 Stack-Info:0000000000000000 Stack-Info:00007FF4313EEE50 Stack-Info:0000000007E1FC68 Stack-Info:0000000000000508 Stack-Info:0000000000000001 Stack-Info:000000000765EB19 Stack-Info:0000000140082100 Stack-Info:0000000000000508 Stack-Info:0000000000000000 Stack-Info:000000005C8CF6C8 Stack-Info:0000000143D2FEA0 Stack-Info:000000000765EA70 Stack-Info:0000000100000000 Stack-Info:0000000000000000 Stack-Info:0000000100000000 Stack-Info:000000005C8CF6C8 Stack-Info:0000000100000033 Stack-Info:0000000143D09A60 Stack-Info:0000000143D2FEE0 Stack-Info:0000000143D09A60 Stack-Info:0000000143D2FEA0 Stack-Info:0000000143D2FE88 Stack-Info:0000000143D2FEB8 Stack-Info:0000000143D09A60 Stack-Info:0000000143D2FEB0 Stack-Info:0000000143D2FED0 Stack-Info:0000000143D2FEC8 Stack-Info:0000000143D2FEF0 Stack-Info:0000000007E1FBF8 Stack-Info:00007FF431461320 Stack-Info:000000000000002A Stack-Info:000000000000002F Stack-Info:0000000007DA00B8 Stack-Info:000000005C8CF301 Stack-Info:0000F8A0EC76FA4C Stack-Info:0000000000000001 Stack-Info:00007FF431848DE0 Stack-Info:0000000007E1FC68 Stack-Info:0000000000000009 Stack-Info:0000000000000000 Stack-Info:0000000000000000 Stack-Info:0000000000000000 Stack-Info:00000001401AFB68 Stack-Info:0000000000000018 Stack-Info:000000014178B4DE Stack-Info:0000000143D2FE88 Stack-Info:0000000143D2FEB8 
[----------------|PyreSpy-ErrorReport|----------------]
Fault Type 0x:00000000C0000005
Fault address:0x0000000141769F02
RAX:0000000000000000
RBX:00000000045DAA48
RCX:0000000000000000
RDX:0000000000000000
RSI:0000000000000004
RDI:00000001439E1788
RBP:00000000045DAF60
RSP:00000000075DE890
R8:00000000075DE7D8
R9:00000000045DAF60
R10:0000000000000000
R11:0000000000000246
R12:00007FF431029B90
R13:00000000045DAE88
R14:00000000045DAE90
R15:0000000000000007
Stack-Info:00000000075DE958 Stack-Info:00000001439E0A80 Stack-Info:00000000075DE7D8 Stack-Info:00000000045DAF60 Stack-Info:0000000007D200C8 Stack-Info:0000000000000000 Stack-Info:0000000007D200C8 Stack-Info:00000000075DEA00 Stack-Info:00000000000000E0 Stack-Info:000000014178B4DE Stack-Info:0000000000000008 Stack-Info:000000014178B4DE Stack-Info:0000000000000000 Stack-Info:0000000144645498 Stack-Info:0000000000000000 Stack-Info:0000000141769E28 Stack-Info:00000000045DAA48 Stack-Info:0000000144645498 Stack-Info:00000000045DAF60 Stack-Info:0000000144645498 Stack-Info:00000000045DAA48 Stack-Info:00000001401B0849 Stack-Info:00000000045DAA48 Stack-Info:0000000000000004 Stack-Info:00000001439E1788 Stack-Info:00000000000000E8 Stack-Info:0000000000000000 Stack-Info:00000001401B0610 Stack-Info:00007FF431029BC0 Stack-Info:0000000144645488 Stack-Info:0000000144917630 Stack-Info:00000000000000C4 Stack-Info:FFFFFFFFFFFFFFFE Stack-Info:000000014000DF31 Stack-Info:FFFFFFFFFFFFFFFE Stack-Info:00000000045DAE90 Stack-Info:0000000000000007 Stack-Info:00000000045DAE90 Stack-Info:0000000000000000 Stack-Info:00000001401AF930 Stack-Info:00000000045DAA48 Stack-Info:00007FF42F15F780 Stack-Info:00000000045DAA38 Stack-Info:00000000045DAA48 Stack-Info:00000000045DAF60 Stack-Info:0000000144645488 Stack-Info:0000000000000000 Stack-Info:0000000143D2FF40 Stack-Info:00000000147E28C4 Stack-Info:00000000045DAE90 Stack-Info:0000000000000007 Stack-Info:0000000000000000 Stack-Info:0000000000000000 Stack-Info:00007FF431029B90 Stack-Info:00000000045DAF60 Stack-Info:00007FF4399DFD14 Stack-Info:0000000000000007 Stack-Info:0000000000000000 Stack-Info:00007FF431207680 Stack-Info:00007FF4399DFD14 Stack-Info:00000000045DAA38 Stack-Info:0000000000000001 Stack-Info:00000000075DEB69 Stack-Info:0000000140082100 

When crashes occurred, I was using
DS4Windows v1.4.52
Intelligent Standby List Cleaner v1.0.2.2
Logitech G HUB
Discord
HanCom Office (it's kind of a Microsoft Word, major suspect)

**Comment by ltw214171** [comment]
[PyresErrorLog.txt](https://github.com/SaucyX/PyreProtecc/files/4536395/PyresErrorLog.txt)

**Comment by ZeroOpcode** [comment]
> [----------------|PyreSpy-ErrorReport|----------------]
> Fault Type 0x:00000000C0000005
> Fault address:0x00000001401AF73D
> RAX:00000000001C2C61
> RBX:0000000000000000
> RCX:000000001C2C61A4
> RDX:00000000000000A4
> RSI:0000000007E1FC68
> RDI:00000000D1A74B90
> RBP:0000000007E1FC68
> RSP:000000000765E980
> R8:0000000007E1FD64
> R9:0000000007E1FD64
> R10:0000000000000508
> R11:0000000144714CF0
> R12:00007FF49E346898
> R13:0000000000000000
> R14:00000000000000FC
> R15:0000000000000009
> Stack-Info:0000000000000009 Stack-Info:0000000143D2FF40 Stack-Info:0000F8A0EC76F8FC Stack-Info:000000014001C24B Stack-Info:0000000000000508 Stack-Info:0000000000000009 Stack-Info:0000000000000001 Stack-Info:0000000143D2FF40 Stack-Info:000000000765EB19 Stack-Info:000000014001C017 Stack-Info:000000000765EAE8 Stack-Info:000000000765EA50 Stack-Info:000000000765EB19 Stack-Info:7FFFFFFF7FFFFFD1 Stack-Info:00007FF4313EEE50 Stack-Info:0000000007E1FC68 Stack-Info:0000000000000009 Stack-Info:0000000000000000 Stack-Info:00007FF4313EEE50 Stack-Info:0000000007E1FC68 Stack-Info:0000000000000508 Stack-Info:0000000000000001 Stack-Info:000000000765EB19 Stack-Info:0000000140082100 Stack-Info:0000000000000508 Stack-Info:0000000000000000 Stack-Info:000000005C8CF6C8 Stack-Info:0000000143D2FEA0 Stack-Info:000000000765EA70 Stack-Info:0000000100000000 Stack-Info:0000000000000000 Stack-Info:0000000100000000 Stack-Info:000000005C8CF6C8 Stack-Info:0000000100000033 Stack-Info:0000000143D09A60 Stack-Info:0000000143D2FEE0 Stack-Info:0000000143D09A60 Stack-Info:0000000143D2FEA0 Stack-Info:0000000143D2FE88 Stack-Info:0000000143D2FEB8 Stack-Info:0000000143D09A60 Stack-Info:0000000143D2FEB0 Stack-Info:0000000143D2FED0 Stack-Info:0000000143D2FEC8 Stack-Info:0000000143D2FEF0 Stack-Info:0000000007E1FBF8 Stack-Info:00007FF431461320 Stack-Info:000000000000002A Stack-Info:000000000000002F Stack-Info:0000000007DA00B8 Stack-Info:000000005C8CF301 Stack-Info:0000F8A0EC76FA4C Stack-Info:0000000000000001 Stack-Info:00007FF431848DE0 Stack-Info:0000000007E1FC68 Stack-Info:0000000000000009 Stack-Info:0000000000000000 Stack-Info:0000000000000000 Stack-Info:0000000000000000 Stack-Info:00000001401AFB68 Stack-Info:0000000000000018 Stack-Info:000000014178B4DE Stack-Info:0000000143D2FE88 Stack-Info:0000000143D2FEB8
> [----------------|PyreSpy-ErrorReport|----------------]
> Fault Type 0x:00000000C0000005
> Fault address:0x0000000141769F02
> RAX:0000000000000000
> RBX:00000000045DAA48
> RCX:0000000000000000
> RDX:0000000000000000
> RSI:0000000000000004
> RDI:00000001439E1788
> RBP:00000000045DAF60
> RSP:00000000075DE890
> R8:00000000075DE7D8
> R9:00000000045DAF60
> R10:0000000000000000
> R11:0000000000000246
> R12:00007FF431029B90
> R13:00000000045DAE88
> R14:00000000045DAE90
> R15:0000000000000007
> Stack-Info:00000000075DE958 Stack-Info:00000001439E0A80 Stack-Info:00000000075DE7D8 Stack-Info:00000000045DAF60 Stack-Info:0000000007D200C8 Stack-Info:0000000000000000 Stack-Info:0000000007D200C8 Stack-Info:00000000075DEA00 Stack-Info:00000000000000E0 Stack-Info:000000014178B4DE Stack-Info:0000000000000008 Stack-Info:000000014178B4DE Stack-Info:0000000000000000 Stack-Info:0000000144645498 Stack-Info:0000000000000000 Stack-Info:0000000141769E28 Stack-Info:00000000045DAA48 Stack-Info:0000000144645498 Stack-Info:00000000045DAF60 Stack-Info:0000000144645498 Stack-Info:00000000045DAA48 Stack-Info:00000001401B0849 Stack-Info:00000000045DAA48 Stack-Info:0000000000000004 Stack-Info:00000001439E1788 Stack-Info:00000000000000E8 Stack-Info:0000000000000000 Stack-Info:00000001401B0610 Stack-Info:00007FF431029BC0 Stack-Info:0000000144645488 Stack-Info:0000000144917630 Stack-Info:00000000000000C4 Stack-Info:FFFFFFFFFFFFFFFE Stack-Info:000000014000DF31 Stack-Info:FFFFFFFFFFFFFFFE Stack-Info:00000000045DAE90 Stack-Info:0000000000000007 Stack-Info:00000000045DAE90 Stack-Info:0000000000000000 Stack-Info:00000001401AF930 Stack-Info:00000000045DAA48 Stack-Info:00007FF42F15F780 Stack-Info:00000000045DAA38 Stack-Info:00000000045DAA48 Stack-Info:00000000045DAF60 Stack-Info:0000000144645488 Stack-Info:0000000000000000 Stack-Info:0000000143D2FF40 Stack-Info:00000000147E28C4 Stack-Info:00000000045DAE90 Stack-Info:0000000000000007 Stack-Info:0000000000000000 Stack-Info:0000000000000000 Stack-Info:00007FF431029B90 Stack-Info:00000000045DAF60 Stack-Info:00007FF4399DFD14 Stack-Info:0000000000000007 Stack-Info:0000000000000000 Stack-Info:00007FF431207680 Stack-Info:00007FF4399DFD14 Stack-Info:00000000045DAA38 Stack-Info:0000000000000001 Stack-Info:00000000075DEB69 Stack-Info:0000000140082100
> When crashes occurred, I was using
> DS4Windows v1.4.52
> Intelligent Standby List Cleaner v1.0.2.2
> Logitech G HUB
> Discord
> HanCom Office (it's kind of a Microsoft Word, major suspect)

Im sorry to hear this happened, Ill investigate the issue and hopefully have it resolved soon! Will you keep you up-to-date . If this crash occurs again before I identify it any information on if you were not connected to anyone / What you were doing / using like you already did ! Much appreciation .

**Comment by ltw214171** [comment]
Crash occurred a few more times, 
[PyresErrorLog.txt](https://github.com/SaucyX/PyreProtecc/files/4541490/PyresErrorLog.txt)

ISLC and DS4Windows and G HUB are suspicious since the game crashed without hancom once.
I don't think it's the discord since if it was you would've already known.
Sadly this is as far as I can get, reinstalling G Hub is a pain in the ass, and I'd like to keep ISLC turned on. And of course I can't even play DS3 without DS4Windows because of the controller

**Comment by 0dm** [comment]
Sorry to hear about your issues with **PyreProtecc**, 

Unfortunately, we have been unable to reproduce this crash through testing, it's most likely being caused by a conflicting application you stated. You may try using the [latest release](https://github.com/SaucyX/PyreProtecc/releases/tag/0.0.3) and see if that helps.
