### ISSUE TITLE
[BUG] Changes game versions and makes window unable to move

### ISSUE THREAD

**Issue by AntonioCS** [SaucyX/PyreProtecc#5]
**Describe the bug**
This has changed the game from Darksouls 3 to Dark Souls 3 The fire fades editions
Not sure why.
Also I use the game in window mode and this messes up the display. I am no longer able to move the window and the fonts aren't definitely as crisp as they were before.
I was using watchdog before and I had none of these side effects.

**To Reproduce**
I just unziped the folder into my Darksouls 3 folder.

**Screenshots**
Before
![image](https://user-images.githubusercontent.com/1086401/82839321-e15e7a80-9ec6-11ea-8c27-2a7d6d2d9c6d.png)
![image](https://user-images.githubusercontent.com/1086401/82839565-b3c60100-9ec7-11ea-813b-b51a1ebab546.png)

After:
![image](https://user-images.githubusercontent.com/1086401/82839392-19fe5400-9ec7-11ea-920e-8878073e5da3.png)
![image](https://user-images.githubusercontent.com/1086401/82839478-6ea1cf00-9ec7-11ea-9501-e148cdc3e4e8.png)

**Additional context**

**Comment by 0dm** [comment]
Hello, @AntonioCS 

The change by PyreProtecc at the main menu of Dark Souls III is intentional as Pyre found it to be "neat" and a way to let you know that the mod works. There's nothing more to it, and it does not grant you any DLC related content. 

Borderless window configuration will be added in the future, for now you can change the game to display in fullscreen and then back to windowed in the settings for a temporary fix.

I'm assuming there are no other issues present, closed.

**Comment by AntonioCS** [comment]
@SaucyX are you serious? You found it neat to change the whole display? I can see that it's working by the console that opens up when the game starts.. and to dismiss such a huge display issue....

I noticed now on the "Other Settings" that you mention that this changes the display... I would just stick to doing one thing and not multiple things as the display change (in my opinion) looks horrible.

I might have been having some problems with watchdog but I'm going back to it.

**Comment by 0dm** [comment]
If you’re referring to the reshade as the “display change”, that can be quickly toggled off in the PyresNightmare file, and there’s even an option in the installer to not use it.

**Comment by AntonioCS** [comment]
I extracted the files from the zip into the directory.

**Comment by 0dm** [comment]
The config file (PyresNightmareOptions) will still be the same then, change the values on the first line and you’ll be fine.

**Comment by AntonioCS** [comment]
I'm already fine, I removed all of the files. Thanks

**Comment by 0dm** [comment]
Glad I could help!
